### ISSUE TITLE
Problem with the latest update

### ISSUE THREAD

**Issue by GaboXandre** [JerichoEdwards/Charcoal-Mod#2]
08:52:54: ERROR[main]: ========== ERROR FROM LUA ===========
08:52:54: ERROR[main]: Failed to load and run script from 
08:52:54: ERROR[main]: /home/gabriel/bin/Minetest/bin/../games/Minetest/mods/charcoal/init.lua:
08:52:54: ERROR[main]: Invalid crafting recipe (output="charcoal:lump 9")
08:52:54: ERROR[main]: stack traceback:
08:52:54: ERROR[main]:  [C]: in function 'register_craft'
08:52:54: ERROR[main]:  ...in/Minetest/bin/../games/Minetest/mods/charcoal/init.lua:24: in main chunk
08:52:54: ERROR[main]: ======= END OF ERROR FROM LUA ========

**Comment by JerichoEdwards** [comment]
Fixed ^-^
